# Generated by Django 4.0.5 on 2022-06-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('user_auto', models.ForeignKey(default='user', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.custom')),
                ('user_company', models.ForeignKey(default='user', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product')),
            ],
        ),
    ]
